name = "streamtape-keeper"
main = "src/index.js"
compatibility_date = "2024-12-01"

# Cron Trigger — 12 နာရီတစ်ခါ auto run
[triggers]
crons = ["0 */12 * * *"]

# KV namespace — dashboard က ဆောက်ပြီး id ထည့်ပါ
[[kv_namespaces]]
binding = "LINKS_KV"
id = "494e4ee9a2674fd4b03b5bbbf4d52264"

# Admin password — dashboard က Settings → Variables မှာ ထည့်ပါ
# သို့မဟုတ် ဒီမှာ တိုက်ရိုက်ထည့်လည်းရတယ် (မလုံခြုံပေမယ့်)
[vars]
ADMIN_PASSWORD = "Romeo183110"
